spring.application.name=app
server.port=8080

# URL de la base de datos (reemplaza 'nombre_tu_base_datos' por el nombre real en Postgres)
spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_gestion_hospitalaria 

# Driver oficial de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Credenciales de acceso
spring.datasource.username=postgres
spring.datasource.password=123456789


# Configuración de Hibernate / JPA
# 'update' actualiza el esquema de la base de datos basándose en tus clases @Entity.
# Si prefieres que Spring Boot no toque tus tablas existentes, puedes cambiarlo a 'none'.
spring.jpa.hibernate.ddl-auto=validate

# Muestra en la consola las consultas SQL que Spring Boot ejecuta automáticamente (muy útil para debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
